#!/usr/bin/env python

from sys import argv
from Simulation import Simulation

if __name__=='__main__':
    if not (len(argv) in [5,6]):
        print 'Usage: ./simulator inst.txt',
        print 'data.txt reg.txt config.txt <result.txt>'
    else:
        sim = Simulation(argv[1],argv[2],argv[3],argv[4])
        if len(argv) == 6:
            sim.Run(fname = argv[5])
        else: sim.Run()